version: '3.3'

services:
  dev_node: &dev_node
    image: node:8
    volumes:
      - "..:/usr/src/app"
    working_dir: /usr/src/app

  node: &node
    <<: *dev_node
    entrypoint: ["node"]
    command: ["--help"]
    expose:
      - "3000"
    ports:
      - "3000:3000"

  npm:
    <<: *dev_node
    entrypoint: ["npm"]
    command: ["--help"]

  nginx:
    container_name: "dev_nginx"
    image: nginx:1.13
    ports:
      - "8888:80"
    expose:
      - "80"
    environment:
      - BACKEND_API_HOST=api1
      - BACKEND_API_PORT=3000
    command: ["bin/sh", "-c", "envsubst '$$BACKEND_API_HOST,$$BACKEND_API_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf &&     nginx -g 'daemon off;'"]
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "../public:/usr/share/nginx/html:ro"
    links:
      - backend_api:api1
    networks:
      - web_dev

  backend_api:
    <<: *node
    container_name: "backend_api"
    command: ["./docker/backend_api/server.js"]
    networks:
      - web_dev

networks:
  web_dev:
    driver: bridge
